import time

import pytest
from jose import jwt

from app.core.config import settings
from app.core.security import create_access_token, decrypt_secret, encrypt_secret, generate_api_key, hash_api_key, hash_password, verify_password
pytestmark = pytest.mark.unit


def test_hash_password_verify_roundtrip_succeeds():
    pwd = "CorrectHorseBatteryStaple123!"
    hashed = hash_password(pwd)
    assert hashed != pwd
    assert hashed.startswith("$2b$")
    assert verify_password(pwd, hashed) is True


def test_verify_password_rejects_wrong_password():
    hashed = hash_password("right-password")
    assert verify_password("wrong-password", hashed) is False


def test_bcrypt_72_byte_limit_enforced_explicitly():
    # Exactly 72 ASCII bytes: succeeds
    pwd_72 = "a" * 72
    hashed = hash_password(pwd_72)
    assert verify_password(pwd_72, hashed) is True

    # 73 ASCII bytes: fails in hash_password
    pwd_73 = "a" * 73
    with pytest.raises(ValueError, match="cannot exceed 72 bytes"):
        hash_password(pwd_73)

    # verify_password never silently truncates and returns False for >72 bytes
    assert verify_password(pwd_73, hashed) is False
    assert verify_password("a" * 80, hashed) is False


def test_bcrypt_unicode_byte_boundaries():
    # '€' is 3 UTF-8 bytes: 24 * 3 = 72 bytes
    pwd_unicode_72 = "€" * 24
    assert len(pwd_unicode_72.encode("utf-8")) == 72
    hashed = hash_password(pwd_unicode_72)
    assert verify_password(pwd_unicode_72, hashed) is True

    # 25 * 3 = 75 bytes: exceeds 72 bytes
    pwd_unicode_75 = "€" * 25
    assert len(pwd_unicode_75.encode("utf-8")) == 75
    with pytest.raises(ValueError, match="cannot exceed 72 bytes"):
        hash_password(pwd_unicode_75)
    assert verify_password(pwd_unicode_75, hashed) is False

    # Emoji '🚀' is 4 UTF-8 bytes: 18 * 4 = 72 bytes
    pwd_emoji_72 = "🚀" * 18
    assert len(pwd_emoji_72.encode("utf-8")) == 72
    hashed_emoji = hash_password(pwd_emoji_72)
    assert verify_password(pwd_emoji_72, hashed_emoji) is True

    pwd_emoji_76 = "🚀" * 19
    with pytest.raises(ValueError, match="cannot exceed 72 bytes"):
        hash_password(pwd_emoji_76)
    assert verify_password(pwd_emoji_76, hashed_emoji) is False


def test_verify_password_malformed_hashes_return_false_safely():
    for bad_hash in [
        "",
        "invalid",
        "12345",
        "$2b$12$",
        "$2b$invalid",
        "$2a$10$",
        "not_a_bcrypt_hash",
        None,
        12345,
    ]:
        assert verify_password("TestPass123!", bad_hash) is False  # type: ignore[arg-type]


def test_verify_password_passlib_fixture_compatibility():
    # Existing $2b$ bcrypt hash generated by passlib: CryptContext(schemes=["bcrypt"]).hash("TestPass123!")
    passlib_fixture_hash = "$2b$12$ohNiPYF1kT2n1OF6/ISwCefNHi3xmm.cd.7X6yORRvxzy7Ga6Tjnq"
    assert verify_password("TestPass123!", passlib_fixture_hash) is True
    assert verify_password("WrongPass123!", passlib_fixture_hash) is False


def test_create_access_token_embeds_subject_and_expiry():
    token = create_access_token("42")
    payload = jwt.decode(token, settings.secret_key, algorithms=["HS256"])
    assert payload["sub"] == "42"
    assert "exp" in payload
    assert payload["exp"] > int(time.time())


def test_generate_api_key_produces_unique_hashed_prefix_triplet():
    raw1, prefix1, digest1 = generate_api_key()
    raw2, prefix2, digest2 = generate_api_key()
    assert raw1 != raw2
    assert raw1.startswith("afaq_")
    assert prefix1 == raw1[:14]
    assert digest1 == hash_api_key(raw1)
    assert digest2 == hash_api_key(raw2)


def test_hash_api_key_is_deterministic_sha256():
    assert hash_api_key("afaq_test") == hash_api_key("afaq_test")
    assert len(hash_api_key("anything")) == 64


def test_encrypt_decrypt_secret_roundtrip():
    secret = "my-super-secret-token-123"
    encrypted = encrypt_secret(secret)
    assert encrypted != secret
    assert decrypt_secret(encrypted) == secret


def test_encrypt_produces_different_ciphertext_for_same_plaintext():
    # Fernet includes random IV, so two encryptions differ but both decrypt correctly
    s = "same value"
    e1 = encrypt_secret(s)
    e2 = encrypt_secret(s)
    assert e1 != e2
    assert decrypt_secret(e1) == s
    assert decrypt_secret(e2) == s